openapi: 3.0.3
info:
  title: API de Atletas
  description: API para gestionar funcionalidades específicas de atletas.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /users/athlete/data/workouthistory:
    get:
      summary: Obtener historial de entrenamientos
      description: Retorna el historial de entrenamientos completados por el atleta.
      parameters:
        - name: user_id
          in: query
          required: true
          description: ID del usuario atleta.
          schema:
            type: string
      responses:
        "200":
          description: Historial de entrenamientos del atleta.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompletionWorkoutStatistic"
        "400":
          description: Parámetros requeridos faltantes.

  /users/athlete/data/diethitory:
    get:
      summary: Obtener historial de dietas
      description: Retorna el historial de dietas seguidas por el atleta.
      parameters:
        - name: user_id
          in: query
          required: true
          description: ID del usuario atleta.
          schema:
            type: string
      responses:
        "200":
          description: Historial de dietas del atleta.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompletionDietStatistics"
        "400":
          description: Parámetros requeridos faltantes.

  /users/athlete/data/sessions:
    get:
      summary: Obtener sesiones próximas
      description: Retorna las sesiones próximas programadas para el atleta.
      parameters:
        - name: user_id
          in: query
          required: true
          description: ID del usuario atleta.
          schema:
            type: string
      responses:
        "200":
          description: Sesiones próximas del atleta.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Session"
        "400":
          description: Parámetros requeridos faltantes.

components:
  schemas:
    CompletionWorkoutStatistic:
      type: object
      properties:
        workout:
          $ref: "#/components/schemas/Workout"
        completeAt:
          type: string
          format: date-time
        assignedAthlete:
          $ref: "#/components/schemas/Athlete"

    CompletionDietStatistics:
      type: object
      properties:
        diet:
          $ref: "#/components/schemas/Diet"
        completeAt:
          type: string
          format: date-time
        asignedAthlete:
          type: integer

    Session:
      type: object
      properties:
        title:
          type: string
        dateTime:
          type: string
          format: date-time
        sessionType:
          type: string
          enum: [WORKOUT, NUTRITION, ASSESSMENT, GROUP, OTHER]
        with:
          type: string
          description: Nombre del atleta
        expectedDuration:
          type: string
          description: Duración esperada en formato ISO
        notes:
          type: array
          items:
            $ref: "#/components/schemas/Note"

    Note:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: "#/components/schemas/User"
        content:
          type: string
        createdAt:
          type: string
          format: date-time

    Workout:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        difficulty:
          type: string
          enum: [EASY, ADVANCE, HARD]
        duration:
          type: string
          description: Duración en formato ISO
        startAt:
          type: string
          format: date-time
        workoutType:
          type: string
          enum: [STRENGTH, CARDIO, FULL_BODY, UPPER_BODY, LOWER_BODY, CORE, FLEXIBILITY, ALL]

    Diet:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        dietType:
          type: string
          enum: [WEIGHT_LOSS, MUSCLE_GAIN, BALANCED, VEGETARIAN, VEGAN, LOW_CARB, PERFORMANCE, ALL]
        duration:
          type: string
          description: Duración en formato ISO
        startAt:
          type: string
          format: date-time

    Athlete:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/User"
        age:
          type: integer
        sex:
          type: string
          enum: [MALE, FEMALE]
        trainingSince:
          type: string
          format: date-time
        allergies:
          type: array
          items:
            $ref: "#/components/schemas/Allergy"
        measurements:
          $ref: "#/components/schemas/Measurements"
        workout:
          $ref: "#/components/schemas/Workout"
        diet:
          $ref: "#/components/schemas/Diet"
        needAssistant:
          type: boolean

    User:
      type: object
      properties:
        id:
          type: integer
        fullname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        creationDate:
          type: string
          format: date-time
        userImageURL:
          type: string
        status:
          $ref: "#/components/schemas/UserStatus"

    UserStatus:
      type: object
      properties:
        state:
          type: string
          enum: [ACTIVE, INACTIVE]
        lastTimeActive:
          type: string
          format: date-time

    Allergy:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Measurements:
      type: object
      properties:
        weight:
          type: number
          format: double
        height:
          type: number
          format: double
        bodyFat:
          type: number
          format: double
        armSize:
          type: number
          format: double
        chest_backSize:
          type: number
          format: double
        hipSize:
          type: number
          format: double
        legSize:
          type: number
          format: double
        calvesSize:
          type: number
          format: double
