openapi: 3.0.3
info:
  title: API de Comunicación
  description: API para gestionar conversaciones, mensajes y sesiones.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /conversations/{conversationId}:
    get:
      summary: Obtener conversación
      description: Obtiene una conversación específica con todos sus mensajes.
      parameters:
        - name: conversationId
          in: path
          required: true
          description: ID de la conversación.
          schema:
            type: integer
      responses:
        "200":
          description: Conversación obtenida exitosamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conversation"
        "400":
          description: ID de conversación inválido.
        "404":
          description: Conversación no encontrada.

  /messages/{messageId}/read:
    post:
      summary: Marcar mensaje como leído
      description: Actualiza el estado de un mensaje a "leído".
      parameters:
        - name: messageId
          in: path
          required: true
          description: ID del mensaje.
          schema:
            type: integer
      responses:
        "200":
          description: Mensaje marcado como leído.
        "400":
          description: ID de mensaje inválido.
        "404":
          description: Mensaje no encontrado.

components:
  schemas:
    Conversation:
      type: object
      properties:
        id:
          type: integer
        trainer:
          $ref: "#/components/schemas/User"
        athlete:
          $ref: "#/components/schemas/User"
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
        lastMessage:
          type: string
          format: date-time

    Message:
      type: object
      properties:
        userName:
          type: string
        sendAt:
          type: string
          format: date-time
        content:
          type: string
        messageStatus:
          type: string
          enum: [SENT, DELIVERED, READ, ALL]

    User:
      type: object
      properties:
        id:
          type: integer
        fullname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        creationDate:
          type: string
          format: date-time
        userImageURL:
          type: string
        status:
          $ref: "#/components/schemas/UserStatus"

    UserStatus:
      type: object
      properties:
        state:
          type: string
          enum: [ACTIVE, INACTIVE]
        lastTimeActive:
          type: string
          format: date-time
