openapi: 3.0.3
info:
  title: API de Entrenamientos
  description: API para gestionar planes de entrenamiento, plantillas y ejercicios.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /workouts:
    get:
      summary: Obtener entrenamientos
      description: Obtiene los entrenamientos asociados a un entrenador.
      parameters:
        - name: trainer_id
          in: query
          required: true
          description: ID del entrenador.
          schema:
            type: string
      responses:
        "200":
          description: Lista de entrenamientos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Workout"
        "400":
          description: Parámetros requeridos faltantes.

  /workouts/plans:
    get:
      summary: Obtener planes de entrenamiento
      description: Obtiene los planes de entrenamiento de un entrenador.
      parameters:
        - name: trainer_id
          in: query
          required: true
          description: ID del entrenador.
          schema:
            type: string
      responses:
        "200":
          description: Lista de planes de entrenamiento.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WorkoutPlan"
        "400":
          description: Parámetros requeridos faltantes.

  /workouts/templates:
    get:
      summary: Obtener plantillas de entrenamiento
      description: Obtiene las plantillas de entrenamiento de un entrenador.
      parameters:
        - name: trainer_id
          in: query
          required: true
          description: ID del entrenador.
          schema:
            type: string
      responses:
        "200":
          description: Lista de plantillas de entrenamiento.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WorkoutTemplate"
        "400":
          description: Parámetros requeridos faltantes.

  /workouts/create:
    post:
      summary: Crear nuevo entrenamiento
      description: Crea un nuevo plan de entrenamiento.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                workout:
                  $ref: "#/components/schemas/WorkoutRequest"
                trainer:
                  $ref: "#/components/schemas/Trainer"
      responses:
        "200":
          description: Entrenamiento creado exitosamente.
        "400":
          description: Error en la solicitud.

components:
  schemas:
    Workout:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        difficulty:
          type: string
          enum: [EASY, ADVANCE, HARD]
        duration:
          type: string
          description: Duración en formato ISO
        startAt:
          type: string
          format: date-time
        workoutType:
          type: string
          enum: [STRENGTH, CARDIO, FULL_BODY, UPPER_BODY, LOWER_BODY, CORE, FLEXIBILITY, ALL]
        exercises:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: "#/components/schemas/WorkoutExercise"
        notes:
          type: array
          items:
            $ref: "#/components/schemas/Note"

    WorkoutPlan:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [STRENGTH, CARDIO, FULL_BODY, UPPER_BODY, LOWER_BODY, CORE, FLEXIBILITY, ALL]
        duration:
          type: string
        frequency:
          type: string
        difficulty:
          type: string
          enum: [EASY, ADVANCE, HARD]
        assignedCount:
          type: integer
        exercises:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: "#/components/schemas/WorkoutExercise"

    WorkoutTemplate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        difficulty:
          type: string
          enum: [EASY, ADVANCE, HARD]
        workoutType:
          type: string
          enum: [STRENGTH, CARDIO, FULL_BODY, UPPER_BODY, LOWER_BODY, CORE, FLEXIBILITY, ALL]
        exercises:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: "#/components/schemas/WorkoutExercise"

    WorkoutRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        difficulty:
          type: string
          enum: [EASY, ADVANCE, HARD]
        duration:
          type: string
          description: Duración en formato ISO
        workoutType:
          type: string
          enum: [STRENGTH, CARDIO, FULL_BODY, UPPER_BODY, LOWER_BODY, CORE, FLEXIBILITY, ALL]

    WorkoutExercise:
      type: object
      properties:
        reps:
          type: integer
        sets:
          type: integer
        isOption:
          type: boolean
        exercise:
          $ref: "#/components/schemas/Exercise"
        notes:
          type: array
          items:
            $ref: "#/components/schemas/Note"

    Exercise:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        bodyPart:
          type: string
          enum: [LEG, ARM, SHOULDER, CORE, BACK, CHEST, FULL_BODY]

    Note:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: "#/components/schemas/User"
        content:
          type: string
        createdAt:
          type: string
          format: date-time

    Trainer:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/User"
        specialization:
          type: string
        yearsOfExperience:
          type: integer

    User:
      type: object
      properties:
        id:
          type: integer
        fullname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        creationDate:
          type: string
          format: date-time
        userImageURL:
          type: string
