services:
    postgres:
        image: postgres:13
        container_name: postgres_db
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: fit-me
        ports:
            - "8080:8080"
        volumes:
            - ./server/src/main/kotlin/es/gaspardev/db:/var/lib/postgresql/data  # Monta la carpeta db del servidor al contenedor
            - postgres_data:/var/lib/postgresql/data  # También puedes mantener el volumen de datos persistente
        networks:
            - postgres_network

volumes:
    postgres_data:

networks:
    postgres_network:
        driver: bridge
